### PR TITLE
Feature/python3

### PR DESCRIPTION
**Pull request by Pike**
The interesting bit here is the removal of funfactory in https://github.com/mozilla/elmo/commit/cc751e1f359c8502a8e2cefc3ddc1bca02952cb1.

The rest is mostly mechanic.

### CODE REVIEW

**Comment by Pike** [comment]
@peterbe, can you take a look at this for old time's sake? I'd love for someone to look at what I'm doing with django-session-csrf, and you might be the last one on the planet to know ;-)

Mostly, is there something in py3 land and dsc that I'm missing, and is the admin site still the right thing to do?

**Comment by peterbe** [comment]
I looked but I don't think I'm confident to make a good judgment. I haven't used or even thought about django-csrf-session in years. 

I personally prefer to avoid the Django Admin. If there's anything I need to do one-off, I ask CloudOps to execute some custom django management command.

Getting rid of funfactory seems like a good idea in general since it's so dated and unsupported. If it works with this change it's probably worth keeping.

**Comment by peterbe** [comment]
In the same vein that I don't bother much with Django Admin, I would also like to share that I've enabled [`black`](https://github.com/ambv/black) on all my active Python projects. It removes and automates all style nits. I still use `pyflakes` but all indentation is managed by bots now. Consider using [therapist](https://github.com/rehandalal/therapist) to make it easier for developers who have different IDEs.

**Comment by Pike** [comment]
I've fixed the comments, thanks, squashed and pushed w/out gh's help.

I might consider `black` for new projects, but for elmo, the diff is too large for the use it's bringing. Mostly due to ' vs ".

**Pull request closed without merging**
